/* ═══════════════════════════════
   MARRAKECH GUIDE — data.js
   Shared data & utilities
   ═══════════════════════════════ */

const KEYS = {
  services: 'mg_services_v3',
  bookings: 'mg_bookings_v3',
};

const DEFAULT_SERVICES = [
  {
    id: 'svc-001',
    title: 'Medina Walking Tour',
    tagline: 'Get lost in 1,000 years of history',
    category: 'Cultural',
    faIcon: 'fa-solid fa-mosque',
    price: 45,
    duration: '3 hours',
    location: 'Old Medina, Marrakech',
    difficulty: 'Easy',
    language: 'EN / FR / AR',
    groupType: 'private',
    maxPeople: 6,
    rating: 4.9,
    reviews: 218,
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?auto=format&fit=crop&w=1400&q=80',
    description: 'Step inside the ancient walled city of Marrakech and let a passionate local guide unravel its layered secrets. The Medina is a UNESCO World Heritage Site that has preserved its medieval soul for over a thousand years — a labyrinth of narrow alleys, hidden courtyards, and centuries-old craft traditions still alive today.',
    longDesc: 'We begin at the iconic Koutoubia Mosque, the tallest minaret in Morocco, before plunging into the heart of the souk quarter. Your guide navigates the winding lanes of the carpet, spice, metalwork, and leather souks — pointing out master craftsmen at work, explaining the bargaining culture, and sharing stories that no guidebook will ever tell you. Midway through, we pause in a shaded fondouk courtyard for a traditional mint tea ceremony — a moment of calm in the beautiful chaos. We finish at the legendary Jemaa el-Fna square, the living heart of Marrakech, just as the evening storytellers and musicians begin to gather.',
    highlights: [
      { icon: 'fa-solid fa-archway', label: 'Koutoubia & Jemaa el-Fna', desc: 'Start and end at Marrakech\'s most iconic landmarks.' },
      { icon: 'fa-solid fa-store', label: 'Spice & Textile Souks', desc: 'Navigate the labyrinthine market districts with an expert guide.' },
      { icon: 'fa-solid fa-mug-hot', label: 'Mint Tea Ceremony', desc: 'Pause for an authentic Moroccan mint tea in a shaded courtyard.' },
      { icon: 'fa-solid fa-door-open', label: 'Hidden Fondouks & Riads', desc: 'Discover doorways invisible to solo travelers.' },
      { icon: 'fa-solid fa-camera', label: 'Best Photography Spots', desc: 'Your guide knows every angle and every light.' },
    ],
    included: ['Certified local guide (3h)', 'Mint tea tasting', 'Souk orientation map', 'Small group (max 6)'],
    notIncluded: ['Hotel transport', 'Shopping budget', 'Gratuities (optional)'],
    meetingPoint: 'Koutoubia Mosque main entrance, Marrakech',
    cancelPolicy: 'Free cancellation up to 24 hours before the tour',
    badge: 'Bestseller',
    whatToBring: 'Comfortable walking shoes, sun cream, water, camera',
    minAge: 'Suitable for all ages',
  },
  {
    id: 'svc-002',
    title: 'High Atlas Mountain Trek',
    tagline: 'Mountains, Berbers & breathtaking ridges',
    category: 'Adventure',
    faIcon: 'fa-solid fa-person-hiking',
    price: 80,
    duration: 'Full day (8h)',
    location: 'Imlil, High Atlas',
    difficulty: 'Moderate',
    language: 'EN / FR',
    groupType: 'group',
    maxPeople: 12,
    rating: 4.8,
    reviews: 154,
    image: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&w=1400&q=80',
    description: 'Lace up your boots and ascend into the dramatic High Atlas range, backbone of Morocco. Rising sharply just 60 kilometres from Marrakech, these mountains are home to the Amazigh (Berber) people — one of Africa\'s oldest indigenous civilizations — who have farmed and pastured these valleys for thousands of years.',
    longDesc: 'We depart Marrakech early to beat the heat and arrive in Imlil village, our trailhead at 1,700 metres. Your certified mountain guide leads the group along ancient mule paths through terraced barley fields, past almond and walnut orchards heavy with fruit, and across crystal-clear mountain streams. We pass through the village of Aroumd clinging to its cliff edge, greet the resident mule teams, and climb to panoramic ridges with sweeping Atlas views. The mid-point is a highlight: a home-cooked lunch with a Berber family in their stone house, sharing tagine, fresh bread, and the warmth of mountain hospitality. We descend by a different route as the late afternoon light turns the mountains amber and gold.',
    highlights: [
      { icon: 'fa-solid fa-mountain', label: 'Peaks above 2,000m', desc: 'Panoramic views of the entire High Atlas range.' },
      { icon: 'fa-solid fa-house-flag', label: 'Amazigh Village Visit', desc: 'Walk through Aroumd village and meet local Berber families.' },
      { icon: 'fa-solid fa-bowl-food', label: 'Home-cooked Berber Lunch', desc: 'Tagine and fresh bread prepared by a mountain family.' },
      { icon: 'fa-solid fa-seedling', label: 'Walnut & Almond Orchards', desc: 'Trek through ancient terraced farming landscapes.' },
      { icon: 'fa-solid fa-van-shuttle', label: 'Transport Included', desc: 'Return transfer from your Marrakech hotel.' },
    ],
    included: ['Licensed mountain guide', 'Return transport from Marrakech', 'Traditional home-cooked lunch', 'Trekking poles on request', 'Water'],
    notIncluded: ['Travel insurance', 'Personal hiking gear', 'Gratuities (optional)'],
    meetingPoint: 'Your hotel in Marrakech (07:00 pickup)',
    cancelPolicy: 'Free cancellation up to 48 hours before',
    badge: 'Top Rated',
    whatToBring: 'Hiking boots or sturdy trainers, layers, sunscreen, water bottle',
    minAge: '8+ years recommended',
  },
  {
    id: 'svc-003',
    title: 'Sahara Desert Overnight',
    tagline: 'Stars, dunes & silence at the edge of the world',
    category: 'Adventure',
    faIcon: 'fa-solid fa-sun',
    price: 160,
    duration: '2 days / 1 night',
    location: 'Merzouga, Erg Chebbi',
    difficulty: 'Easy',
    language: 'EN / FR / AR',
    groupType: 'group',
    maxPeople: 8,
    rating: 5.0,
    reviews: 97,
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80',
    description: 'The Sahara is a place of impossible beauty and profound silence. The great orange dunes of Erg Chebbi rise to over 150 metres near the village of Merzouga in southeast Morocco — one of the most spectacular desert landscapes on Earth. This overnight journey takes you there and back in two unforgettable days.',
    longDesc: 'Day one: we depart Marrakech and cross the High Atlas via the spectacular Tizi n\'Tichka pass (2,260m) before descending into the pre-Saharan steppe and kasbahs of the Draa Valley. We arrive at the dune edge at golden hour. You mount your camel for a sunset ride into the heart of Erg Chebbi, accompanied by your Berber camel guide. Camp is your private luxury tent — a real bed, soft linens, lantern light. The evening unfolds around a campfire with Gnawa drumming, mint tea, and a sky so dense with stars it feels painted. Morning: wake before dawn and climb the highest dune for a sunrise that will stay with you forever. Camel back, breakfast, and the return journey — you arrive in Marrakech late evening.',
    highlights: [
      { icon: 'fa-solid fa-horse', label: 'Sunset Camel Trek', desc: 'Ride into the dunes as the desert turns gold and copper.' },
      { icon: 'fa-solid fa-tent', label: 'Luxury Desert Camp', desc: 'Private tent with a real bed, lanterns, and soft furnishings.' },
      { icon: 'fa-solid fa-music', label: 'Gnawa Music Evening', desc: 'Traditional Moroccan desert music around the campfire.' },
      { icon: 'fa-solid fa-star', label: 'Stargazing Session', desc: 'Zero light pollution — the Milky Way visible to the naked eye.' },
      { icon: 'fa-solid fa-cloud-sun', label: 'Sahara Sunrise', desc: 'Wake at dawn and climb the dunes for a once-in-a-lifetime view.' },
    ],
    included: ['Return transport from Marrakech', 'Luxury private tent (1 night)', 'All meals (dinner + breakfast)', 'Sunset & sunrise camel ride', 'Guide & camel handler'],
    notIncluded: ['Alcoholic beverages', 'Personal expenses', 'Travel insurance'],
    meetingPoint: 'Your hotel in Marrakech (06:00 pickup — Day 1)',
    cancelPolicy: 'Free cancellation up to 72 hours before',
    badge: '⭐ 5.0',
    whatToBring: 'Warm layer for the desert night, sunscreen, headtorch, camera',
    minAge: 'Suitable for all ages',
  },
  {
    id: 'svc-004',
    title: 'Private Bespoke Tour',
    tagline: 'Your Marrakech, your rules',
    category: 'Private',
    faIcon: 'fa-solid fa-crown',
    price: 120,
    duration: 'Flexible (4–10h)',
    location: 'Marrakech & region',
    difficulty: 'Any level',
    language: 'EN / FR / AR / ES / DE',
    groupType: 'private',
    maxPeople: 4,
    rating: 4.9,
    reviews: 63,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1400&q=80',
    description: 'No group. No fixed itinerary. No compromise. Your dedicated private guide and vehicle are entirely at your service, adapting to your pace, your curiosity, and your schedule from the moment you step out of your hotel.',
    longDesc: 'Architecture enthusiast? We spend the morning in the Ben Youssef Madrasa, the Bahia Palace, and every painted cedar ceiling in the Medina — moving as slowly as you want. Foodie? We do a dawn market tour, visit the herb women, choose ingredients together, and cook lunch in a riad kitchen. Photographer? We know every rooftop, every blue door, every souq shaft of light and the exact time to be there. History lover? We trace the city from its 11th-century Almoravid foundations to its role in the trans-Saharan gold trade. This is Morocco without compromise — seen through your eyes, explained by someone who was born and raised here.',
    highlights: [
      { icon: 'fa-solid fa-pencil', label: 'Fully Custom Itinerary', desc: 'Designed entirely around your interests before you arrive.' },
      { icon: 'fa-solid fa-car', label: 'Private Vehicle & Driver', desc: 'Air-conditioned vehicle for the full duration.' },
      { icon: 'fa-solid fa-shield-halved', label: '100% Private — No Sharing', desc: 'You and your group only — never joined by strangers.' },
      { icon: 'fa-solid fa-language', label: '5 Languages Available', desc: 'EN, FR, AR, ES, DE — your guide speaks your language.' },
      { icon: 'fa-solid fa-key', label: 'Insider Access', desc: 'Doors and places not accessible to the regular public.' },
    ],
    included: ['Private certified guide', 'Private air-conditioned vehicle', 'Hotel pick-up & drop-off', 'Flexible start time', 'Personal concierge service'],
    notIncluded: ['Entry fees', 'Meals & drinks', 'Gratuities (optional)'],
    meetingPoint: 'Your hotel in Marrakech (time of your choice)',
    cancelPolicy: 'Free cancellation up to 24 hours before',
    badge: 'Premium',
    whatToBring: 'Comfortable shoes, sunscreen, camera',
    minAge: 'Suitable for all ages and abilities',
  },
  {
    id: 'svc-005',
    title: 'Moroccan Cooking Class',
    tagline: 'From souk to table — master tagine & more',
    category: 'Food & Culture',
    faIcon: 'fa-solid fa-utensils',
    price: 70,
    duration: '4 hours',
    location: 'Riad Kitchen, Medina',
    difficulty: 'Easy',
    language: 'EN / FR',
    groupType: 'group',
    maxPeople: 8,
    rating: 4.8,
    reviews: 189,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1400&q=80',
    description: 'Moroccan cuisine is one of the world\'s great culinary traditions — a blend of Amazigh, Arab, Andalusian, and sub-Saharan African influences refined over centuries. This hands-on class takes you to the source: the spice souk, the herb market, and a riad kitchen, where you\'ll cook and eat a full Moroccan feast.',
    longDesc: 'We begin at Mouassine spice souk, where our expert chef guides you through the aromas of over 40 spices — ras el hanout, preserved lemons, argan oil, chermoula — explaining how each is used and letting you taste, smell, and choose your own ingredients. Then into our beautiful riad kitchen: terracotta tiles, copper pots, the scent of cumin in the air. You\'ll cook chicken tagine with preserved lemon and olives, vegetable couscous with seven vegetables, zaalouk (roasted aubergine salad), and bastilla (the legendary Moroccan sweet-savoury pastry). We eat together at the long table, with fresh Moroccan bread, olives, and as much mint tea as you can drink. Take home a printed recipe booklet — and the confidence to recreate it all at home.',
    highlights: [
      { icon: 'fa-solid fa-basket-shopping', label: 'Spice Souk Visit', desc: 'Hand-pick your own ingredients with the chef\'s guidance.' },
      { icon: 'fa-solid fa-hat-chef', label: 'Expert Moroccan Chef', desc: 'Learn from someone who has cooked these dishes since childhood.' },
      { icon: 'fa-solid fa-fire-burner', label: 'Cook Tagine, Couscous & Bastilla', desc: 'Three iconic Moroccan recipes in one session.' },
      { icon: 'fa-solid fa-book-open', label: 'Printed Recipe Booklet', desc: 'Take home all recipes to recreate at home.' },
      { icon: 'fa-solid fa-plate-wheat', label: 'Feast on What You Cook', desc: 'Eat together at the table — the best reward.' },
    ],
    included: ['Market tour with chef', 'All ingredients', 'Full cooking class', 'The full meal you prepare', 'Mint tea, juices & bread', 'Recipe booklet'],
    notIncluded: ['Hotel transport', 'Alcoholic beverages', 'Gratuities'],
    meetingPoint: 'Mouassine Fountain, Medina (10:00 AM)',
    cancelPolicy: 'Free cancellation up to 24 hours before',
    badge: null,
    whatToBring: 'Appetite! (no equipment needed, everything provided)',
    minAge: 'Suitable for all ages — great for families',
  },
  {
    id: 'svc-006',
    title: 'Traditional Hammam & Spa',
    tagline: 'A thousand-year purification ritual',
    category: 'Wellness',
    faIcon: 'fa-solid fa-spa',
    price: 55,
    duration: '2.5 hours',
    location: 'Traditional Hammam, Medina',
    difficulty: 'Easy',
    language: 'EN / FR / AR',
    groupType: 'private',
    maxPeople: 2,
    rating: 4.7,
    reviews: 142,
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1400&q=80',
    description: 'The hammam is not just a bath — it is a social institution, a meditative ritual, and a full-body restoration that Moroccans have practiced for over a thousand years. Unlike a modern spa, a traditional hammam works with steam, marble heat, and centuries-old techniques that leave you genuinely renewed.',
    longDesc: 'You are welcomed with mint tea and shown to the changing rooms. The hammam operates across three marble rooms, each progressively hotter, drawing toxins to the surface and relaxing deep muscle tension. Your kessala (hammam attendant) guides you through the kessa scrub — a vigorous exfoliation with a special woven glove and black beldi soap made from pure olive oil — that removes weeks of dead skin in minutes. A ghassoul clay mask follows, drawing impurities and leaving skin luminous. The final treatment is a full-body argan oil massage — Morocco\'s liquid gold, pressed from the nuts of argan trees found only in this region. You emerge to a quiet resting room, wrapped in warm towels, with fresh mint tea and honey pastries.',
    highlights: [
      { icon: 'fa-solid fa-temperature-high', label: 'Traditional Steam Rooms', desc: 'Three marble rooms in ascending heat — a full detox.' },
      { icon: 'fa-solid fa-hands', label: 'Black Soap & Kessa Scrub', desc: 'The most effective exfoliation you will ever experience.' },
      { icon: 'fa-solid fa-leaf', label: 'Argan Oil Massage', desc: 'Morocco\'s liquid gold — full-body relaxation.' },
      { icon: 'fa-solid fa-face-smile-relaxed', label: 'Ghassoul Clay Mask', desc: 'Volcanic clay mask for deep pore cleansing.' },
      { icon: 'fa-solid fa-mug-hot', label: 'Mint Tea & Pastries', desc: 'Rest and recover with tea and traditional sweets.' },
    ],
    included: ['Full hammam ritual (steam + scrub + mask)', 'Towels & robe', 'Argan oil full-body massage', 'Mint tea & Moroccan pastries'],
    notIncluded: ['Hotel transport', 'Personal toiletries', 'Gratuities'],
    meetingPoint: 'Address sent by WhatsApp after booking',
    cancelPolicy: 'Free cancellation up to 24 hours before',
    badge: null,
    whatToBring: 'Swimming costume or underwear (for the hammam room)',
    minAge: '16+ years',
  },
  {
    id: 'svc-007',
    title: 'Ourika Valley Escape',
    tagline: 'Waterfalls, markets & mountain air',
    category: 'Nature',
    faIcon: 'fa-solid fa-water',
    price: 65,
    duration: 'Full day (7h)',
    location: 'Ourika Valley, 30km south',
    difficulty: 'Easy',
    language: 'EN / FR / AR',
    groupType: 'group',
    maxPeople: 14,
    rating: 4.7,
    reviews: 211,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1400&q=80',
    description: 'Just 30 kilometres south of the heat and dust of Marrakech, the Ourika Valley is a startling transformation: lush green terraces rising from a fast-flowing river, Berber villages clinging to terracotta cliffs, and the crisp scent of the High Atlas on the breeze. A perfect escape from the city.',
    longDesc: 'We depart Marrakech and quickly leave the city behind, entering the Atlas foothills as the road climbs along the Ourika River. Along the route, we stop at a roadside Berber women\'s cooperative producing argan oil — you\'ll see the traditional extraction process and taste fresh argan oil and amlou (almond-argan paste) with bread. Further up the valley, we visit the weekly Berber market at Setti Fatma village — a colourful gathering of mountain producers selling everything from fresh produce to handwoven baskets. We then hike up the gorge behind the village to reach the seven cascading waterfalls of Setti Fatma — a series of beautiful natural pools perfect for photos. Lunch is a long, lazy affair at a riverside terrace restaurant: freshly caught Atlas mountain trout, salads, and fresh Moroccan bread.',
    highlights: [
      { icon: 'fa-solid fa-droplet', label: 'Setti Fatma Waterfalls', desc: 'Seven magnificent waterfall tiers in a dramatic gorge.' },
      { icon: 'fa-solid fa-tree', label: 'Valley & River Trails', desc: 'Easy riverside walks through lush mountain scenery.' },
      { icon: 'fa-solid fa-shop', label: 'Berber Weekly Market', desc: 'Authentic mountain market with local producers.' },
      { icon: 'fa-solid fa-fish', label: 'Riverside Trout Lunch', desc: 'Fresh Atlas mountain trout at a riverside terrace.' },
      { icon: 'fa-solid fa-jar', label: 'Argan Oil Cooperative', desc: 'See traditional argan oil extraction and taste fresh oil.' },
    ],
    included: ['Return transport from Marrakech', 'Expert guide', 'Waterfall hike', 'Argan cooperative visit', 'Market stop'],
    notIncluded: ['Lunch (recommended: ~150 MAD)', 'Entry fees', 'Gratuities'],
    meetingPoint: 'Your hotel in Marrakech (08:30 pickup)',
    cancelPolicy: 'Free cancellation up to 24 hours before',
    badge: null,
    whatToBring: 'Comfortable shoes for the waterfall hike, swimwear (optional), sunscreen',
    minAge: 'Suitable for all ages',
  },
  {
    id: 'svc-008',
    title: 'Essaouira Coastal Day Trip',
    tagline: 'Wind City — ocean, art & blue boats',
    category: 'Cultural',
    faIcon: 'fa-solid fa-sailboat',
    price: 75,
    duration: 'Full day (10h)',
    location: 'Essaouira, Atlantic Coast',
    difficulty: 'Easy',
    language: 'EN / FR',
    groupType: 'group',
    maxPeople: 16,
    rating: 4.8,
    reviews: 178,
    image: 'https://images.unsplash.com/photo-1597212618440-806262de1507?auto=format&fit=crop&w=1400&q=80',
    description: 'Three hours west of Marrakech on the Atlantic coast lies Essaouira — the UNESCO-listed "Wind City of Africa." White-washed ramparts, cobalt-blue wooden boats, and a breeze that never stops: this is a Morocco utterly different from the inland imperial cities.',
    longDesc: 'We depart Marrakech early and cross the argan forest — home to the famous tree-climbing goats that balance impossibly in the branches to reach the fruit. In Essaouira, we walk the UNESCO medina: its Portuguese-era sea bastions, cannon-lined ramparts, and whitewashed lanes lined with art galleries and craft studios. Your guide explains the city\'s extraordinary history as a hub of the trans-Saharan gold and salt trade, and its more recent incarnation as a counter-culture haven (Jimi Hendrix and Orson Welles both lived here). We visit the working harbour — one of Morocco\'s most photogenic — where blue-painted wooden fishing boats are repaired and painted by hand. Lunch is grilled sardines, calamari and fresh fish straight off the boats. The afternoon is free: wander the galleries, walk the Atlantic beach, or simply sit on the ramparts and feel the ocean wind.',
    highlights: [
      { icon: 'fa-solid fa-fort-awesome', label: 'UNESCO Medina & Ramparts', desc: 'Explore the fortified old city and its iconic sea bastions.' },
      { icon: 'fa-solid fa-anchor', label: 'Working Harbour & Fish Market', desc: 'One of Morocco\'s most atmospheric and photogenic harbours.' },
      { icon: 'fa-solid fa-palette', label: 'Art Galleries & Gnawa Music', desc: 'Essaouira is Morocco\'s bohemian art capital.' },
      { icon: 'fa-solid fa-wind', label: 'Atlantic Ocean & Beach', desc: 'Walk the long white beach with the famous Atlantic wind.' },
      { icon: 'fa-solid fa-goat', label: 'Tree-Climbing Goats', desc: 'Stop to see goats climbing argan trees on the road.' },
    ],
    included: ['Return transport from Marrakech', 'Expert guide', 'City orientation walk', 'Free time in the afternoon'],
    notIncluded: ['Lunch (recommended: grilled fish at harbour ~100 MAD)', 'Entry fees', 'Gratuities'],
    meetingPoint: 'Your hotel in Marrakech (07:30 pickup)',
    cancelPolicy: 'Free cancellation up to 48 hours before',
    badge: null,
    whatToBring: 'A windproof layer (Essaouira is windy year-round!), sunscreen, camera',
    minAge: 'Suitable for all ages',
  },
  {
    id: 'svc-009',
    title: 'Sunrise Hot Air Balloon',
    tagline: 'Float above the Atlas plains at dawn',
    category: 'Adventure',
    faIcon: 'fa-solid fa-circle-dot',
    price: 200,
    duration: '4 hours (incl. transfer)',
    location: 'Marrakech Plains',
    difficulty: 'Easy',
    language: 'EN / FR',
    groupType: 'group',
    maxPeople: 8,
    rating: 4.9,
    reviews: 88,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1400&q=80',
    description: 'Rise silently into the Marrakech dawn sky and watch the High Atlas mountains catch their first gold light. This is a Marrakech that no ground-level traveller ever sees — ancient walls, palm groves, patchwork Berber villages, and the shimmering plains stretching to the horizon.',
    longDesc: 'You are collected from your hotel before sunrise and driven to the launch site on the Haouz plain south of Marrakech. You watch the balloon inflate in the growing light — itself a beautiful spectacle of fire, colour, and geometry. Once airborne, you drift silently at the mercy of the wind, rising above 300 metres as the sun clears the Atlas ridge and turns everything amber. Your experienced pilot narrates the landscape: the ancient city walls, the palmery, the ksar villages, the irrigation channels that have watered these plains since the 11th century. The one-hour flight ends with a champagne-style landing in a field, followed by a Berber breakfast laid out on rugs in the open air — fresh msemen flatbread, honey, argan oil, orange juice, and coffee. You receive your official first-flight certificate before being driven back to your hotel.',
    highlights: [
      { icon: 'fa-solid fa-circle-notch', label: '1-Hour Balloon Flight', desc: 'Drift silently above the Marrakech plains at sunrise.' },
      { icon: 'fa-solid fa-mountain-sun', label: 'Atlas Sunrise Views', desc: 'Watch the mountains catch their first golden light.' },
      { icon: 'fa-solid fa-bread-slice', label: 'Berber Breakfast on Landing', desc: 'A feast of Moroccan flatbread, honey, and argan oil on rugs in the open air.' },
      { icon: 'fa-solid fa-certificate', label: 'Official Flight Certificate', desc: 'A keepsake of your first (or next!) hot air balloon flight.' },
      { icon: 'fa-solid fa-shuttle-van', label: 'Hotel Transfer Included', desc: 'Pre-dawn pickup and return drop-off at your door.' },
    ],
    included: ['Pre-dawn hotel transfer', '1-hour balloon flight', 'Berber breakfast on landing', 'Sparkling wine (adults)', 'Flight certificate', 'Full insurance'],
    notIncluded: ['Gratuities (optional)', 'Personal expenses'],
    meetingPoint: 'Your hotel (04:30 AM pickup — dawn flight)',
    cancelPolicy: 'Free cancellation up to 72h (weather dependent — full refund if weather cancellation)',
    badge: 'Exclusive',
    whatToBring: 'Warm layer for the early morning, camera, comfortable flat shoes',
    minAge: '6+ years',
  },
  {
    id: 'svc-010',
    title: 'Palaces & Gardens Tour',
    tagline: 'Marble, mosaics & rose water fountains',
    category: 'Cultural',
    faIcon: 'fa-solid fa-building-columns',
    price: 50,
    duration: '3.5 hours',
    location: 'Marrakech Medina',
    difficulty: 'Easy',
    language: 'EN / FR / AR / ES',
    groupType: 'private',
    maxPeople: 6,
    rating: 4.8,
    reviews: 134,
    image: 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1400&q=80',
    description: 'Marrakech was built to impress. The city\'s sultans and warlords competed for centuries to build the most magnificent palaces and gardens — and many survive in extraordinary condition. This tour brings them all together in one deeply satisfying morning of architecture, history, and beauty.',
    longDesc: 'We begin at the Bahia Palace — "The Brilliant" — built in the 1890s for the Grand Vizier Ahmed ibn Moussa as the finest palace in all of Morocco. Its 8 hectares encompass 150 rooms, painted cedar ceilings in every shade, intricate zellij tile floors, and lush orange-tree courtyards. Next, the haunting ruins of El Badi Palace — "The Incomparable" — built by Sultan Ahmed al-Mansour after his victory over Portugal in 1578, then deliberately demolished by his successor and its 360 rooms stripped to the walls. The emptiness is extraordinary and moving. The Saadian Tombs — discovered by aerial survey in 1917, sealed for 300 years — contain the elaborately decorated marble mausoleums of the Saadian dynasty. We finish in the gardens: the geometric perfection of Majorelle\'s cobalt-blue garden (and Berber Museum), and the meditative Menara olive groves with their 900-year-old pavilion.',
    highlights: [
      { icon: 'fa-solid fa-landmark', label: 'Bahia Palace', desc: 'The finest 19th-century palace in Morocco — painted cedar ceilings and orange-tree courts.' },
      { icon: 'fa-solid fa-chess-rook', label: 'El Badi Palace Ruins', desc: '400 years of haunting, stripped grandeur on the floor of history.' },
      { icon: 'fa-solid fa-cross', label: 'Saadian Tombs', desc: 'Sealed for 300 years, discovered 1917 — one of Marrakech\'s greatest secrets.' },
      { icon: 'fa-solid fa-circle-half-stroke', label: 'Majorelle Garden', desc: 'The cobalt-blue paradise created by Jacques Majorelle and restored by Yves Saint Laurent.' },
      { icon: 'fa-solid fa-tree', label: 'Berber Museum & Menara Gardens', desc: 'Amazigh culture and 900-year-old olive groves.' },
    ],
    included: ['Expert guide (3.5h)', 'Majorelle Garden & Berber Museum entry', 'Small group (max 6)'],
    notIncluded: ['Bahia Palace entry (~70 MAD)', 'Hotel transport', 'Gratuities'],
    meetingPoint: 'Koutoubia Mosque gardens (09:00 AM)',
    cancelPolicy: 'Free cancellation up to 24 hours before',
    badge: null,
    whatToBring: 'Comfortable walking shoes, sun protection, camera',
    minAge: 'Suitable for all ages',
  },
];

const DEFAULT_BOOKINGS = [
  {
    id: 'bk-001', serviceId: 'svc-001', serviceTitle: 'Medina Walking Tour',
    customerName: 'Sophie Bernard', email: 'sophie@example.com', phone: '+33612345678',
    date: daysFromNow(1), people: 2, total: 90, status: 'confirmed', payment: 'card',
    createdAt: new Date().toISOString(), notes: ''
  },
  {
    id: 'bk-002', serviceId: 'svc-002', serviceTitle: 'High Atlas Mountain Trek',
    customerName: 'James Miller', email: 'james@example.com', phone: '+44771234567',
    date: daysFromNow(3), people: 4, total: 320, status: 'pending', payment: 'demo',
    createdAt: new Date().toISOString(), notes: 'Vegetarian lunch requested'
  },
  {
    id: 'bk-003', serviceId: 'svc-009', serviceTitle: 'Sunrise Hot Air Balloon',
    customerName: 'Leila Hassan', email: 'leila@example.com', phone: '+212612345678',
    date: daysFromNow(5), people: 2, total: 400, status: 'pending', payment: 'demo',
    createdAt: new Date().toISOString(), notes: ''
  },
  {
    id: 'bk-004', serviceId: 'svc-005', serviceTitle: 'Moroccan Cooking Class',
    customerName: 'Marco Ricci', email: 'marco@example.com', phone: '+393312345678',
    date: daysFromNow(2), people: 3, total: 210, status: 'confirmed', payment: 'card',
    createdAt: new Date().toISOString(), notes: 'Gluten-free adaptation needed'
  },
  {
    id: 'bk-005', serviceId: 'svc-003', serviceTitle: 'Sahara Desert Overnight',
    customerName: 'Emma Schulz', email: 'emma@example.com', phone: '+491712345678',
    date: daysFromNow(8), people: 2, total: 320, status: 'cancelled', payment: 'demo',
    createdAt: new Date().toISOString(), notes: ''
  },
];

/* ── UTILITIES ── */
function daysFromNow(n) {
  const d = new Date(); d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}
function todayISO() { return new Date().toISOString().slice(0, 10); }
function loadData(key, fallback) {
  try { const r = localStorage.getItem(key); return r ? JSON.parse(r) : JSON.parse(JSON.stringify(fallback)); }
  catch { return JSON.parse(JSON.stringify(fallback)); }
}
function saveData(key, val) { localStorage.setItem(key, JSON.stringify(val)); }
function money(val) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);
}
function getCategoryIcon(cat) {
  const m = { Cultural:'fa-mosque', Adventure:'fa-person-hiking', Private:'fa-crown', 'Food & Culture':'fa-utensils', Wellness:'fa-spa', Nature:'fa-leaf' };
  return m[cat] || 'fa-star';
}
function toast(msg, type = '') {
  document.querySelectorAll('.toast').forEach(t => t.remove());
  const el = document.createElement('div');
  el.className = `toast ${type}`; el.textContent = msg;
  document.body.appendChild(el);
  requestAnimationFrame(() => el.classList.add('show'));
  setTimeout(() => { el.classList.remove('show'); setTimeout(() => el.remove(), 400); }, 3200);
}
function seedDemoData() {
  saveData(KEYS.services, JSON.parse(JSON.stringify(DEFAULT_SERVICES)));
  saveData(KEYS.bookings, JSON.parse(JSON.stringify(DEFAULT_BOOKINGS)));
}
